Exception in thread "main" java.lang.RuntimeException: detonate on ERR_INTERNAL
	at JhwScm.raiseError(JhwScm.java:3747)
	at JhwScm.cons(JhwScm.java:3266)
	at JhwScm.store(JhwScm.java:3529)
	at JhwScm.gosub(JhwScm.java:3669)
	at JhwScm.step(JhwScm.java:300)
	at Computer.drive(Computer.java:73)
	at TestScm.expect(TestScm.java:1456)
	at TestScm.expect(TestScm.java:1318)
	at TestScm.main(TestScm.java:121)
