Exception in thread "main" java.lang.RuntimeException: drive failure on "(let ((a 10) (b a)) b)": expected -4 got 0
	at Util.assertEquals(Util.java:97)
	at TestScm.expect(TestScm.java:1496)
	at TestScm.batch(TestScm.java:1296)
	at TestScm.metabatch(TestScm.java:1306)
	at TestScm.main(TestScm.java:852)
